name: Build and Deploy

on:
  workflow_dispatch:  # 允许手动触发
#  push:
#    branches:
#     - matser  # 当 matser 分支有 push 事件时触发

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # 关键步骤：必须添加，否则没有代码文件


    - name: Run a one-line script
      run: echo Hello, world!
    - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
      run: |
          npm install
          npm run build

#    - name: Deploy 🚀
#      uses: JamesIves/github-pages-deploy-action@v4
#      with:
#      folder: build # The folder the action should deploy.
#  job2:
#    runs-on: ubuntu-latest
#    steps:
#    - run: node --version

 # build:
#    runs-on: ubuntu-latest  # 使用 Ubuntu 最新版运行环境

    