name: Build and Deploy

on:
  #workflow_dispatch:  # 允许手动触发
  push:
    branches:
      - matser  # 当 matser 分支有 push 事件时触发

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - run: pwd
    - run: ls
  job2:
    steps:
    - run : node --version

 # build:
#    runs-on: ubuntu-latest  # 使用 Ubuntu 最新版运行环境

    